# Generated by Django 5.2.8 on 2026-01-21 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualStatusMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='状態コード')),
                ('name', models.CharField(max_length=50, verbose_name='状態名')),
            ],
            options={
                'verbose_name': 'マニュアル状態マスタ',
                'verbose_name_plural': 'マニュアル状態マスタ',
            },
        ),
        migrations.CreateModel(
            name='ManualVisibilityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='範囲コード')),
                ('name', models.CharField(max_length=100, verbose_name='範囲名')),
            ],
            options={
                'verbose_name': 'マニュアル公開範囲マスタ',
                'verbose_name_plural': 'マニュアル公開範囲マスタ',
            },
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='マニュアル名')),
                ('description', models.TextField(blank=True, verbose_name='説明・備考')),
                ('file', models.FileField(upload_to='manuals/', verbose_name='ファイル')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='論理削除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='承認日時')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_manuals', to=settings.AUTH_USER_MODEL, verbose_name='承認者')),
                ('bookmarks', models.ManyToManyField(blank=True, related_name='bookmarked_manuals', to=settings.AUTH_USER_MODEL, verbose_name='ブックマーク')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_manuals', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department', verbose_name='関連部署')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='manuals.manualstatusmaster', verbose_name='状態')),
                ('visibility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='manuals.manualvisibilitymaster', verbose_name='公開範囲')),
            ],
            options={
                'verbose_name': 'マニュアル',
                'verbose_name_plural': 'マニュアル',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ViewingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True, verbose_name='最終閲覧日時')),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuals.manual', verbose_name='閲覧マニュアル')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='閲覧ユーザー')),
            ],
            options={
                'verbose_name': '閲覧履歴',
                'verbose_name_plural': '閲覧履歴',
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'manual')},
            },
        ),
    ]
