# Generated by Django 5.2.8 on 2026-01-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0002_manualfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='manuals/', verbose_name='ファイル'),
        ),
    ]
