# Generated by Django 5.2.8 on 2026-01-21 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEventTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='種別コード')),
                ('name', models.CharField(max_length=50, verbose_name='種別名')),
            ],
            options={
                'verbose_name': 'スケジュール種別マスタ',
                'verbose_name_plural': 'スケジュール種別マスタ',
            },
        ),
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='予定タイトル')),
                ('description', models.TextField(blank=True, verbose_name='詳細')),
                ('start_at', models.DateTimeField(verbose_name='開始日時')),
                ('end_at', models.DateTimeField(verbose_name='終了日時')),
                ('is_private', models.BooleanField(default=False, verbose_name='非公開')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_events', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('event_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='schedule.scheduleeventtypemaster', verbose_name='種類')),
            ],
            options={
                'verbose_name': 'スケジュール',
                'verbose_name_plural': 'スケジュール',
            },
        ),
    ]
