# Generated by Django 5.2.8 on 2026-01-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='category',
            field=models.CharField(choices=[('personal', '個人的 (不在)'), ('work', '仕事 (予定あり)')], default='work', max_length=20, verbose_name='カテゴリ'),
        ),
    ]
