# Generated by Django 5.2.8 on 2026-01-21 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewStatusMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='状態コード')),
                ('name', models.CharField(max_length=50, verbose_name='状態名')),
            ],
            options={
                'verbose_name': '面談状態マスタ',
                'verbose_name_plural': '面談状態マスタ',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(verbose_name='面談日時')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('notes', models.TextField(blank=True, verbose_name='面談メモ')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_interviews', to=settings.AUTH_USER_MODEL, verbose_name='対象部下')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_interviews', to=settings.AUTH_USER_MODEL, verbose_name='担当上司')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interviews.interviewstatusmaster', verbose_name='状態')),
            ],
            options={
                'verbose_name': '面談',
                'verbose_name_plural': '面談',
            },
        ),
    ]
