# Generated by Django 5.2.8 on 2026-01-22 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='script_generated',
            field=models.TextField(blank=True, null=True, verbose_name='AI生成スクリプト'),
        ),
        migrations.AddField(
            model_name='interview',
            name='theme',
            field=models.CharField(blank=True, max_length=100, verbose_name='面談テーマ'),
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.IntegerField(choices=[(3, 'うまくいった'), (2, '普通・保留'), (1, '失敗・イマイチ')], verbose_name='総合評価')),
                ('tags', models.JSONField(default=list, verbose_name='反応タグ')),
                ('memo', models.TextField(blank=True, verbose_name='一言メモ')),
                ('ai_analysis_log', models.TextField(blank=True, null=True, verbose_name='AI分析ログ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='interviews.interview', verbose_name='対象面談')),
            ],
            options={
                'verbose_name': '面談フィードバック',
                'verbose_name_plural': '面談フィードバック',
            },
        ),
        migrations.CreateModel(
            name='MemberAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_text', models.TextField(blank=True, verbose_name='AI分析テキスト（取説）')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('target_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_analysis', to=settings.AUTH_USER_MODEL, verbose_name='対象部下')),
            ],
            options={
                'verbose_name': '部下分析データ',
                'verbose_name_plural': '部下分析データ',
            },
        ),
    ]
