# Generated by Django 5.2.8 on 2026-01-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interview_script_generated_interview_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='場所'),
        ),
    ]
