# Generated by Django 5.2.8 on 2026-01-21 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationStatusMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='状態コード')),
                ('name', models.CharField(max_length=50, verbose_name='状態名')),
            ],
            options={
                'verbose_name': '相談状態マスタ',
                'verbose_name_plural': '相談状態マスタ',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='相談タイトル')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_consultations', to=settings.AUTH_USER_MODEL, verbose_name='質問者')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responded_consultations', to=settings.AUTH_USER_MODEL, verbose_name='回答者')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='consultations.consultationstatusmaster', verbose_name='状態')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='メッセージ内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='consultations.consultation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='質問タイトル(要約)')),
                ('problem_summary', models.TextField(verbose_name='課題・質問内容')),
                ('solution_summary', models.TextField(verbose_name='解決策・操作手順')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('source_consultation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.consultation', verbose_name='元チャット')),
                ('tags', models.ManyToManyField(blank=True, related_name='questions', to='tasks.tag', verbose_name='関連タグ')),
            ],
            options={
                'verbose_name': 'ナレッジ(解決済質問)',
                'verbose_name_plural': 'ナレッジ(解決済質問)',
            },
        ),
    ]
