# Generated by Django 5.2.8 on 2026-01-21 02:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='グループ名(部署名)')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
            ],
            options={
                'verbose_name': 'グループ',
                'verbose_name_plural': 'グループ',
            },
        ),
        migrations.CreateModel(
            name='RoleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='役割コード')),
                ('name', models.CharField(max_length=50, verbose_name='役割名')),
            ],
            options={
                'verbose_name': '役割マスタ',
                'verbose_name_plural': '役割マスタ',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('employee_number', models.CharField(help_text='例: 000-000-000', max_length=20, unique=True, verbose_name='社員番号')),
                ('last_name', models.CharField(max_length=50, verbose_name='姓')),
                ('first_name', models.CharField(max_length=50, verbose_name='名')),
                ('last_name_kana', models.CharField(max_length=50, verbose_name='セイ')),
                ('first_name_kana', models.CharField(max_length=50, verbose_name='メイ')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='電話番号')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='アイコン画像')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入社日')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('is_initial_setup_completed', models.BooleanField(default=False, verbose_name='初回設定完了')),
                ('temp_password_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='仮パスワード有効期限')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('is_staff', models.BooleanField(default=False, verbose_name='管理サイトアクセス権限')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department', verbose_name='所属グループ')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.rolemaster', verbose_name='権限')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
            },
        ),
    ]
