# Generated by Django 5.2.8 on 2026-01-21 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='タイプコード')),
                ('name', models.CharField(max_length=100, verbose_name='タイプ名')),
            ],
            options={
                'verbose_name': '通知タイプマスタ',
                'verbose_name_plural': '通知タイプマスタ',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('message', models.TextField(verbose_name='本文')),
                ('related_object_id', models.IntegerField(blank=True, null=True, verbose_name='関連ID')),
                ('link_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='リンクURL')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='通知日時')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='通知先')),
                ('notification_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='notifications.notificationtypemaster', verbose_name='通知タイプ')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
    ]
