# Generated by Django 5.2.8 on 2026-01-21 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='タグ名')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskStatusMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='状態コード')),
                ('name', models.CharField(max_length=50, verbose_name='状態名')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
            ],
            options={
                'verbose_name': 'タスク状態マスタ',
                'verbose_name_plural': 'タスク状態マスタ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TaskTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='種別コード')),
                ('name', models.CharField(max_length=50, verbose_name='種別名')),
            ],
            options={
                'verbose_name': 'タスク種別マスタ',
                'verbose_name_plural': 'タスク種別マスタ',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タスク名')),
                ('due_date', models.DateTimeField(verbose_name='期限')),
                ('notes', models.TextField(blank=True, verbose_name='タスク備考欄')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='取り掛かり中の人')),
                ('completed_users', models.ManyToManyField(blank=True, related_name='completed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='完了とした人')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_tasks', to=settings.AUTH_USER_MODEL, verbose_name='依頼者')),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='tasks.tag', verbose_name='タグ')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.taskstatusmaster', verbose_name='タスク状態')),
                ('task_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.tasktypemaster', verbose_name='タスク種別')),
            ],
            options={
                'verbose_name': 'タスク',
                'verbose_name_plural': 'タスク',
                'ordering': ['due_date', 'status'],
            },
        ),
    ]
